
package com.gdc.robothelper.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SisproRobotManagerHelper", targetNamespace = "http://webservice.robothelper.gdc.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SisproRobotManagerHelper {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getApplications();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getFlowsByApplicationId(
        @WebParam(name = "arg0", partName = "arg0")
        long arg0);

}
