
package com.gdc.robothelper.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SRMHelper", targetNamespace = "http://webservice.robothelper.gdc.com/", wsdlLocation = "http://192.168.207.41:8080/robothelper/SRMHelper?wsdl")
public class SRMHelper
    extends Service
{

    private final static URL SRMHELPER_WSDL_LOCATION;
    private final static WebServiceException SRMHELPER_EXCEPTION;
    private final static QName SRMHELPER_QNAME = new QName("http://webservice.robothelper.gdc.com/", "SRMHelper");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.207.41:8080/robothelper/SRMHelper?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRMHELPER_WSDL_LOCATION = url;
        SRMHELPER_EXCEPTION = e;
    }

    public SRMHelper() {
        super(__getWsdlLocation(), SRMHELPER_QNAME);
    }

    public SRMHelper(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRMHELPER_QNAME, features);
    }

    public SRMHelper(URL wsdlLocation) {
        super(wsdlLocation, SRMHELPER_QNAME);
    }

    public SRMHelper(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRMHELPER_QNAME, features);
    }

    public SRMHelper(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SRMHelper(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SisproRobotManagerHelper
     */
    @WebEndpoint(name = "SisproRobotManagerHelperPort")
    public SisproRobotManagerHelper getSisproRobotManagerHelperPort() {
        return super.getPort(new QName("http://webservice.robothelper.gdc.com/", "SisproRobotManagerHelperPort"), SisproRobotManagerHelper.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SisproRobotManagerHelper
     */
    @WebEndpoint(name = "SisproRobotManagerHelperPort")
    public SisproRobotManagerHelper getSisproRobotManagerHelperPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.robothelper.gdc.com/", "SisproRobotManagerHelperPort"), SisproRobotManagerHelper.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRMHELPER_EXCEPTION!= null) {
            throw SRMHELPER_EXCEPTION;
        }
        return SRMHELPER_WSDL_LOCATION;
    }

}
