
package com.gdc.robothelper.webservice.robot;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Multirecarga", targetNamespace = "http://localhost/webservice/status/", wsdlLocation = "https://samyg2test.sispro.mx/wsendusersamyg2/wssamyg/status/soapFlujosV2.php?wsdl")
public class Multirecarga
    extends Service
{

    private final static URL MULTIRECARGA_WSDL_LOCATION;
    private final static WebServiceException MULTIRECARGA_EXCEPTION;
    private final static QName MULTIRECARGA_QNAME = new QName("http://localhost/webservice/status/", "Multirecarga");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://samyg2test.sispro.mx/wsendusersamyg2/wssamyg/status/soapFlujosV2.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MULTIRECARGA_WSDL_LOCATION = url;
        MULTIRECARGA_EXCEPTION = e;
    }

    public Multirecarga() {
        super(__getWsdlLocation(), MULTIRECARGA_QNAME);
    }

    public Multirecarga(WebServiceFeature... features) {
        super(__getWsdlLocation(), MULTIRECARGA_QNAME, features);
    }

    public Multirecarga(URL wsdlLocation) {
        super(wsdlLocation, MULTIRECARGA_QNAME);
    }

    public Multirecarga(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MULTIRECARGA_QNAME, features);
    }

    public Multirecarga(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Multirecarga(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MultirecargaPortType
     */
    @WebEndpoint(name = "MultirecargaPort")
    public MultirecargaPortType getMultirecargaPort() {
        return super.getPort(new QName("http://localhost/webservice/status/", "MultirecargaPort"), MultirecargaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultirecargaPortType
     */
    @WebEndpoint(name = "MultirecargaPort")
    public MultirecargaPortType getMultirecargaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/webservice/status/", "MultirecargaPort"), MultirecargaPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MULTIRECARGA_EXCEPTION!= null) {
            throw MULTIRECARGA_EXCEPTION;
        }
        return MULTIRECARGA_WSDL_LOCATION;
    }

}
